name: music_app
description: iTunes top 100 albums music app

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.18.0 <3.0.0'


dependencies:
  cupertino_icons: ^1.0.2
  http: ^0.13.5
  webview_flutter: ^4.0.2
  cached_network_image: ^3.2.3
  connectivity_plus: ^3.0.2

  flutter:
    sdk: flutter



dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.0


flutter:
  uses-material-design: true
